package assignment3;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sam_e
 */
public class GUI extends javax.swing.JFrame {
    Camping javaCamping;
    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        javaCamping = new Camping();
        javaCamping.Load();
        String checkedInGuests = javaCamping.GetCheckedInGuests();
        taCheckedInGuests.setText(checkedInGuests);
        String recentlyCheckedOutCabins = javaCamping.GetRecentlyCheckedOutCabins();
        taNewlyCheckedOutCabins.setText(recentlyCheckedOutCabins);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCheckIn = new javax.swing.JButton();
        btnCheckOut = new javax.swing.JButton();
        btnShowCabins = new javax.swing.JButton();
        btnShowPricelist = new javax.swing.JButton();
        btnChangePrices = new javax.swing.JButton();
        btnShowIncome = new javax.swing.JButton();
        btnShowStays = new javax.swing.JButton();
        lblCheckedInGuests = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taCheckedInGuests = new javax.swing.JTextArea();
        lblNewlyCheckedOutCabins = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        taNewlyCheckedOutCabins = new javax.swing.JTextArea();
        btnClearList = new javax.swing.JButton();
        btnShowPreviousGuests = new javax.swing.JButton();
        btnShowGuesInfo = new javax.swing.JButton();
        lblJavaCamping = new javax.swing.JLabel();
        btnShowAllGuests = new javax.swing.JButton();
        lblGuestInfo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCheckIn.setText("Incheckning");
        btnCheckIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckInActionPerformed(evt);
            }
        });

        btnCheckOut.setText("Utcheckning");
        btnCheckOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckOutActionPerformed(evt);
            }
        });

        btnShowCabins.setText("Visa alla stugor");
        btnShowCabins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowCabinsActionPerformed(evt);
            }
        });

        btnShowPricelist.setText("Visa prislista");
        btnShowPricelist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowPricelistActionPerformed(evt);
            }
        });

        btnChangePrices.setText("Ändra priser");
        btnChangePrices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangePricesActionPerformed(evt);
            }
        });

        btnShowIncome.setText("Visa intäkter");
        btnShowIncome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowIncomeActionPerformed(evt);
            }
        });

        btnShowStays.setText("Visa gästnätter");
        btnShowStays.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowStaysActionPerformed(evt);
            }
        });

        lblCheckedInGuests.setText("Incheckade Gäster");

        taCheckedInGuests.setColumns(20);
        taCheckedInGuests.setRows(5);
        jScrollPane1.setViewportView(taCheckedInGuests);

        lblNewlyCheckedOutCabins.setText("Nyligen utcheckade stugor");

        taNewlyCheckedOutCabins.setColumns(20);
        taNewlyCheckedOutCabins.setRows(5);
        jScrollPane2.setViewportView(taNewlyCheckedOutCabins);

        btnClearList.setText("Rensa");
        btnClearList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearListActionPerformed(evt);
            }
        });

        btnShowPreviousGuests.setText("Visa tidigare");
        btnShowPreviousGuests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowPreviousGuestsActionPerformed(evt);
            }
        });

        btnShowGuesInfo.setText("Visa Info");
        btnShowGuesInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowGuesInfoActionPerformed(evt);
            }
        });

        lblJavaCamping.setText("Java Camping");

        btnShowAllGuests.setText("Visa Samtliga");
        btnShowAllGuests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowAllGuestsActionPerformed(evt);
            }
        });

        lblGuestInfo.setText("Gäster");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnShowCabins, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnShowAllGuests, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnShowPreviousGuests, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnShowGuesInfo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(btnCheckOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCheckIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblGuestInfo)
                        .addGap(34, 34, 34)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCheckedInGuests)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnShowPricelist)
                        .addGap(30, 30, 30)
                        .addComponent(btnChangePrices, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblNewlyCheckedOutCabins))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnClearList)
                        .addGap(11, 11, 11))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnShowIncome)
                        .addGap(30, 30, 30)
                        .addComponent(btnShowStays)))
                .addGap(55, 55, 55))
            .addGroup(layout.createSequentialGroup()
                .addGap(306, 306, 306)
                .addComponent(lblJavaCamping)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblJavaCamping)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNewlyCheckedOutCabins)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClearList)
                        .addGap(82, 82, 82)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnChangePrices)
                            .addComponent(btnShowPricelist))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnShowStays)
                            .addComponent(btnShowIncome)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCheckedInGuests)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCheckIn)
                                .addGap(22, 22, 22)
                                .addComponent(btnCheckOut)
                                .addGap(26, 26, 26)
                                .addComponent(btnShowCabins)
                                .addGap(101, 101, 101)
                                .addComponent(lblGuestInfo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnShowGuesInfo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnShowPreviousGuests)
                                .addGap(7, 7, 7)
                                .addComponent(btnShowAllGuests))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCheckInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckInActionPerformed
        javaCamping.GuestCheckIn();
        String checkedInGuests = javaCamping.GetCheckedInGuests();
        taCheckedInGuests.setText(checkedInGuests);
        javaCamping.Save();
    }//GEN-LAST:event_btnCheckInActionPerformed

    private void btnCheckOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckOutActionPerformed
        javaCamping.GuestCheckOut();
        String checkedInGuests = javaCamping.GetCheckedInGuests();
        taCheckedInGuests.setText(checkedInGuests);
        String recentlyCheckedOutCabins = javaCamping.GetRecentlyCheckedOutCabins();
        taNewlyCheckedOutCabins.setText(recentlyCheckedOutCabins);
        javaCamping.Save();
    }//GEN-LAST:event_btnCheckOutActionPerformed

    private void btnClearListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearListActionPerformed
        javaCamping.ClearListRecentlyCheckedOutCabins();
        String recentlyCheckedOutCabins = javaCamping.GetRecentlyCheckedOutCabins();
        taNewlyCheckedOutCabins.setText(recentlyCheckedOutCabins);
        javaCamping.Save();
    }//GEN-LAST:event_btnClearListActionPerformed

    private void btnShowPreviousGuestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowPreviousGuestsActionPerformed
        javaCamping.ShowPreviousGuestInfo();
    }//GEN-LAST:event_btnShowPreviousGuestsActionPerformed

    private void btnShowGuesInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowGuesInfoActionPerformed
        javaCamping.ShowCurrentGuestInfo();
    }//GEN-LAST:event_btnShowGuesInfoActionPerformed

    private void btnShowAllGuestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowAllGuestsActionPerformed
        javaCamping.ShowAllGuestInfo();
    }//GEN-LAST:event_btnShowAllGuestsActionPerformed

    private void btnShowCabinsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowCabinsActionPerformed
        javaCamping.ShowAllCabins();
    }//GEN-LAST:event_btnShowCabinsActionPerformed

    private void btnShowPricelistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowPricelistActionPerformed
        javaCamping.ShowPriceList();
    }//GEN-LAST:event_btnShowPricelistActionPerformed

    private void btnChangePricesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePricesActionPerformed
        javaCamping.EditPriceList();
        javaCamping.Save();
    }//GEN-LAST:event_btnChangePricesActionPerformed

    private void btnShowIncomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowIncomeActionPerformed
        javaCamping.ShowIncome();
    }//GEN-LAST:event_btnShowIncomeActionPerformed

    private void btnShowStaysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowStaysActionPerformed
        javaCamping.ShowNights();
    }//GEN-LAST:event_btnShowStaysActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChangePrices;
    private javax.swing.JButton btnCheckIn;
    private javax.swing.JButton btnCheckOut;
    private javax.swing.JButton btnClearList;
    private javax.swing.JButton btnShowAllGuests;
    private javax.swing.JButton btnShowCabins;
    private javax.swing.JButton btnShowGuesInfo;
    private javax.swing.JButton btnShowIncome;
    private javax.swing.JButton btnShowPreviousGuests;
    private javax.swing.JButton btnShowPricelist;
    private javax.swing.JButton btnShowStays;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCheckedInGuests;
    private javax.swing.JLabel lblGuestInfo;
    private javax.swing.JLabel lblJavaCamping;
    private javax.swing.JLabel lblNewlyCheckedOutCabins;
    private javax.swing.JTextArea taCheckedInGuests;
    private javax.swing.JTextArea taNewlyCheckedOutCabins;
    // End of variables declaration//GEN-END:variables
}
